name: Kernel Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install required dependencies
      run: |
        sudo apt update
        sudo apt install -y bash curl grep coreutils hostname procps lz4 brotli flex bc cpio kmod ccache zip libtinfo6 python3
        sudo apt upgrade

    - name: Set executable permission for build script
      run: chmod +x do_build.sh ckbuild.sh

    - name: Run Kernel Build Script
      env:
        TZ: Asia/Jakarta
      run: ./do_build.sh ginkgo ktc

    - name: Upload output files (zImage, Image.gz-dtb, etc)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kernel-output
        path: |
          out/arch/arm64/boot/*
